version: "3.9"

services:
  database:
    image: postgres:10-alpine
    volumes:
      - db_seven:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_mem
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "45533:5432"

volumes:
  db_seven: